### ISSUE TITLE
changeDistance example errors

### ISSUE THREAD

**Issue by antmedellin** [cubert-hyperspectral/cuvis.sdk#33]
I was trying this [example](https://github.com/cubert-hyperspectral/Cuvis-SDK/blob/main/Cpp/Examples/04_changeDistance_cpp/main.cpp) with the cornfields dataset and kept getting an error with 'proc.calc_distance(distance);'. Error message: 'error: invalid argument exception' . Example shows that datatype is an int, but cuvis.hpp looks like it is expecting a double datatype. When I tried using a double datatype, the error persisted. 

As a side note, the expected units should be included in the documentation in the example. I am assuming that the expected units are millimeters, per the variable name in cuvis.hpp.

**Comment by birkholz-cubert** [comment]
Closing this for now as probably not relevant anymore.
