### ISSUE TITLE
Export Reflectance Example

### ISSUE THREAD

**Issue by antmedellin** [cubert-hyperspectral/cuvis.sdk#34]
Is there a way to process a .cu3 image and export the reflectance data to a multi page tiff image? My [attempt](https://github.com/tamu-edu-students/HyperTools/blob/anthony_dev/examples/cubert_export_tiff.cpp) shows that the data cube is processed for reflectance, but the exported image does not match what is visualized. The exported images are very dark in color. Is there an additional arg I have to set before exporting, so that the reflectance data is exported instead of the raw data?

**Comment by birkholz-cubert** [comment]
Closing this for now as probably not relevant anymore.
