### ISSUE TITLE
Proposal: Renaming Python package.

### ISSUE THREAD

**Issue by BenMGeo** [cubert-hyperspectral/cuvis.sdk#37]
based on the new naming convention(s), I suggest the following action for the python subpackage.

1. The sdk functionalities (measurement, acquisition context, etc) will be ported to the submodule cuvis.sdk
2. the classificator functionalities will be ported to the submodule cuvis.ai (as far as I understood)
3. the examples will be the ported to the main cuvis package as functionalities.

the package will have the following look for the user:

`import cuvis` provides examples to run the camera with.
`import cuvis.sdk` provides all sdk functionalities
`import cuvis.ai` provides the classificator (maybe we should divide the ai part into multiple submodules?)

**Comment by birkholz-cubert** [comment]
Closing, as not relevant anymore.
