### ISSUE TITLE
Issues installing 3.2.0.1 on Ubuntu

### ISSUE THREAD

**Issue by antmedellin** [cubert-hyperspectral/cuvis.sdk#47]
Files located [here](https://cloud.cubert-gmbh.de/index.php/s/kKVtx0x2fmYqVgx?path=%2FUbuntu%2020.04)
I am able to install cuviscommon, but libcuvis and libcuvisxx require a forced overwrite to install. Error is below. Both packages had a similar error. Needed to use sudo dpkg -i --force-overwrite to install the two lib files. 

dpkg: error processing archive /home/anthony/Downlo
ads/Ubuntu 20.04/libcuvis_3.2.0-1.deb (--unpack):
 trying to overwrite '/usr/share/man/man3/log.3.gz'
, which is also in package manpages-dev 5.05-1
Errors were encountered while processing:
 /home/anthony/Downloads/Ubuntu 20.04/libcuvis_3.2.
0-1.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by robertCubert** [comment]
Thanks for raising the issue, I will take a look!

**Comment by robertCubert** [comment]
This is fixed and will be resolved with the next minor version!
