### ISSUE TITLE
Pthread error with CPP Example 06

### ISSUE THREAD

**Issue by antmedellin** [cubert-hyperspectral/cuvis.sdk#53]
[Example 6](https://github.com/cubert-hyperspectral/cuvis.sdk/tree/main/Cpp/Examples/06_recordVideo_cpp) fails to build. 

Error: /usr/bin/ld: CMakeFiles/main.dir/main.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

The following line should be added to the CMakeLists file
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")

**Comment by birkholz-cubert** [comment]
See https://github.com/cubert-hyperspectral/cuvis.cpp/pull/4
