### ISSUE TITLE
cuvis.python needs to use newer version

### ISSUE THREAD

**Issue by antmedellin** [cubert-hyperspectral/cuvis.sdk#55]
[cuvis.python @ 490a495](https://github.com/cubert-hyperspectral/cuvis.python/tree/490a495c518b85896fdf49da32d9e2e8c40f5af5)

The setup file uses VERSION = '3.2.1b3'

whereas the current main branch uses VERSION = '3.2.1b4'

**Comment by BenMGeo** [comment]
@birkholz-cubert can you check that?

**Comment by birkholz-cubert** [comment]
done with release of v3.2.1
