### ISSUE TITLE
Cuvis 3.3 in a Docker Container Based on Ubuntu 22.04

### ISSUE THREAD

**Issue by saqibshakil** [cubert-hyperspectral/cuvis.sdk#68]
I have created an image from Ubuntu 22.04 and installed the sdk.
I want to run a simulation of it. 
It compiles fine but does not return measurements

Logs

`

    loading user settings...
    Emitting event "chat" [/]
    loading session file ...
    No CUDA device found.
    Emitting event "chat" [/]
    loading calibration (factory)...
    Emitting event "chat" [/]
    loading acquisition context...
    Loading product 'Ultris S5'
    Project dispersion image
    Processing dispersion cache  0.00%
    Processing dispersion cache 10.53%
    Processing dispersion cache 21.05%
    Processing dispersion cache 31.58%
    Processing dispersion cache 42.11%
    Processing dispersion cache 52.63%
    Processing dispersion cache 63.16%
    Processing dispersion cache 73.68%
    Processing dispersion cache 84.21%
    Processing dispersion cache 94.74%
    LutManager is using CpuLutProcessor.
    Using "Lens" calibration.
    Using default cubalize algorithm 'lut'.
    *** Ultris S5 => loaded ***
    Processing context loaded Ultris S5, serial number is 'BS5234701'.
    Emitting event "chat" [/]
    Prepare processing of measurements...
    Verify distance calibration.
    Project dispersion image
    Processing dispersion cache  0.00%
    Processing dispersion cache 10.53%
    Processing dispersion cache 21.05%
    Processing dispersion cache 31.58%
    Processing dispersion cache 42.11%
    Processing dispersion cache 52.63%
    Processing dispersion cache 63.16%
    Processing dispersion cache 73.68%
    Processing dispersion cache 84.21%
    Processing dispersion cache 94.74%
    Emitting event "chat" [/]
    Waiting for camera to come online...
    Emitting event "chat" [/]
    Emitting event "chat" [/]
    Component details:
    Emitting event "chat" [/]
    initializing hardware...
    Emitting event "chat" [/]
    configuring worker...
    Emitting event "chat" [/]
    Recording and transmitting...! 
    camera is Online
    From camera  2.68 Hz | Defective:   0.00%
    From camera  2.67 Hz | Defective:   0.00%

`

Code

`

    import os
    import platform
    import asyncio as a
    import cuvis
    from stream.cuvis.processMesu import processMesu 
    
    from stream.AbstractStream import AbstractStream
    from config.cuvis import cuvisConfig
    
    
    data_dir = None
    lib_dir = None
    
    if platform.system() == "Windows":
        lib_dir = os.getenv("CUVIS")
        data_dir = os.path.normpath(os.path.join(lib_dir, os.path.pardir, "sdk",
                                                 "sample_data", "set_examples"))
    elif platform.system() == "Linux":
        lib_dir = os.getenv("CUVIS_DATA")
        data_dir = cuvisConfig["data_dir"]
    
    loc_factory = os.path.join(data_dir, cuvisConfig["factory"])
    loc_settings = os.path.join(data_dir, cuvisConfig["setting"])
    
    loc_output = os.path.join(os.getcwd(), "EX06_video")
    
    dark_file = os.path.join(os.getcwd(), "data", "calib", "Dark.cu3s")
    white_file = os.path.join(os.getcwd(),"data", "calib", "White.cu3s")
    
    measurementLoc = os.path.join(os.getcwd(), cuvisConfig["sessionFile"])
    
    
    loc_exptime = 10 #in ms
    loc_autoexp = False
    loc_fps = 10
    
    global triggerExp
    global postMeasure
    
    
    class SessionStream(AbstractStream):
    
        def __init__(self, event,
                                            emit,
                                            userSettingsDir=loc_settings,
                                            factoryDir=loc_factory,
                                            recDir=loc_output,
                                            exposure=loc_exptime,
                                            autoExp=loc_autoexp,
                                            fps=loc_fps,
                                            triggerExport=lambda x: True,
                                            processAnalytics=lambda x: True,
                                            mode=2, # RAW
                                            distance=300):
            self.emit = emit
            self.userSettingsDir = userSettingsDir
            self.factoryDir=factoryDir
            self.recDir=recDir
            self.exposure=exposure
            self.autoExp=autoExp
            self.fps=fps
            self.triggerExport=triggerExport
            self.processAnalytics=processAnalytics
            self.mode=mode
            self.distance=distance
            self.event = event
            super().__init__()
    
        async def state_changed_callback(state, component_states):
            print(f'camera is {state.name}')
    
        async def start_stream(self):
            await self.emit("loading user settings...")
            cuvis.init(self.userSettingsDir)
            cuvis.set_log_level("debug")
    
        
            await self.emit("loading session file ...")
            session = cuvis.SessionFile(measurementLoc)
            await self.emit("loading calibration (factory)...")
            calibration = cuvis.Calibration(self.factoryDir)
    
            await self.emit("loading acquisition context...")
            acquisitionContext = cuvis.AcquisitionContext(session, simulate=True)
            session_info = cuvis.SessionData('video',0,0)
            acquisitionContext.session_info = session_info
    
            processingContext = cuvis.ProcessingContext(calibration)
            
            # try:
            #     await self.emit("loading dark reference...")
            #     sessionDk = cuvis.SessionFile(dark_file)
            #     dark = sessionDk[0]
            #     assert dark._handle
            #     processingContext.set_reference(dark, cuvis.ReferenceType.Dark)
            # except Exception as e:
            #     await self.emit(f"Error: {e}")    
            
            # try:
            #     await self.emit("loading white reference...")
            #     sessionWt = cuvis.SessionFile(white_file)
            #     white = sessionWt[0]
            #     assert white._handle
            #     processingContext.set_reference(white, cuvis.ReferenceType.White)
            # except Exception as e:
            #     await self.emit(f"Error: {e}")    
            
            await self.emit("Prepare processing of measurements...")
            
            processingArgs = cuvis.ProcessingArgs(allow_recalib=False, processing_mode=cuvis.ProcessingMode(self.mode))
            processingContext.set_processing_args(processingArgs)
            processingContext.calc_distance(self.distance)
            
            def state_changed_callback(state, component_states):
                print(f'camera is {state.name}')
            acquisitionContext.register_state_change_callback(state_changed_callback)
    
            await self.emit("Waiting for camera to come online...")
    
            while acquisitionContext.state == cuvis.HardwareState.Offline:
                print(".")
                await a.sleep(1)
            await self.emit("\n")
    
            await self.emit("Component details:")
            for i, comp in enumerate(acquisitionContext.components()):
                print("Component #{} {} is {}".format(i, comp.info.display_name,
                                                    "online" if comp.online else "offline"))
                print(" -- info:        {}".format(comp.info.sensor_info))
                print(" -- use:         {}".format(comp.info.user_field))
                print(" -- pixelformat: {}".format(comp.info.pixel_format))
    
            await self.emit("initializing hardware...")
            await acquisitionContext.set_integration_time_async(self.exposure)
            await acquisitionContext.set_operation_mode_async(cuvis.OperationMode.Internal)
            await acquisitionContext.set_fps_async(self.fps)
            await acquisitionContext.set_auto_exp_async(self.autoExp)
            await acquisitionContext.set_continuous_async(True)
    
            await self.emit("configuring worker...")
            workerSettings = cuvis.WorkerSettings(
            #                                             poll_intervall=10,
            #                                             worker_count=10,
            #                                             hard_limit=10,
            #                                             soft_limit=10,
                                                        
                                                        can_skip_measurements=False,
                                                        can_drop_results=False
            )
            worker = cuvis.Worker(workerSettings)
            worker.set_acquisition_context(acquisitionContext)
            worker.set_processing_context(processingContext)
            # worker.set_exporter(cubeExporter)
    
            await self.emit("Recording and transmitting...! ")
    
            async def process(workerContainer:  cuvis.WorkerResult):
                if workerContainer.mesu.data is not None:
                    try:
                        await processMesu(workerContainer.mesu, processAnalytics=self.processAnalytics, triggerExport=self.triggerExport, seqNo=workerContainer.mesu.session_info.sequence_number)
                    except Exception as e:
                        print(e)
            
            
            worker.register_worker_callback(process)
    
            for _ in range(20000000):
                # pretend to read some data
                # workerContainer = worker.get_next_result(200)
                
                await a.sleep(1)
                if self.event.is_set():
                    worker.reset_worker_callback()
                    await self.emit("Stream stopped.")
                    await acquisitionContext.set_continuous_async(False)
                    cuvis.shutdown()
                    return
    
                    
            
            worker.reset_worker_callback()
    
            await self.emit("Stream stopped.")
            await acquisitionContext.set_continuous_async(False)
            await self.emit("finished.")
            cuvis.shutdown()
            pass
`

**Comment by saqibshakil** [comment]
I expect the worker to call the process function but it never does.
The code most of it works fine on 3.2

**Comment by saqibshakil** [comment]
Having same issues with EX07 from python examples

**Comment by BenMGeo** [comment]
Hi @saqibshakil

So you have a virtual machine running Ubuntu 22.04? Have you checked forwarding of the data from the ethernet port is correct?

@manke-cubert @birkholz-cubert , can you check the code?

**Comment by saqibshakil** [comment]
As I am just running a simulation, it should not be an issue.

**Comment by saqibshakil** [comment]
Yes worker.start processig worked. How soon can you update the parameter definition for worker as I am having some issues around it as well.

**Comment by birkholz-cubert** [comment]
Currently there is a version called `3.3.1rc1` for `cuvis` on pypi available. While this is not an official release yet it should fix the things you mentioned. You can install it via `pip install cuvis --pre`
